DROP TABLE IF EXISTS PRODUCT;
DROP SEQUENCE IF EXISTS PRODUCT_SEQ;

CREATE SEQUENCE PRODUCT_SEQ START WITH 0 INCREMENT BY 1;

CREATE TABLE PRODUCT (
    ID BIGINT DEFAULT NEXT VALUE FOR PRODUCT_SEQ PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRICE DOUBLE,
    QUANTITY INT,
    VERSION BIGINT DEFAULT 0
);

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Laptop', 'High-end laptop', 1500.0, 5);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Mouse', 'Wireless mouse', 25.0, 50);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Keyboard', 'Mechanical keyboard', 75.0, 20);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Monitor', '24-inch LED monitor', 200.0, 15);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Printer', 'Laser printer', 120.0, 10);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Webcam', 'HD webcam', 60.0, 30);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Headphones', 'Noise-cancelling headphones', 150.0, 25);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Speakers', 'Bluetooth speakers', 80.0, 40);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('External HDD', '1TB external hard drive', 90.0, 20);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('USB Drive', '64GB USB 3.0', 15.0, 100);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Tablet', '10-inch Android tablet', 250.0, 12);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Smartphone', 'Latest model smartphone', 900.0, 8);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Charger', 'Fast USB-C charger', 30.0, 60);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Router', 'Wi-Fi 6 router', 180.0, 10);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Projector', 'HD projector', 400.0, 5);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Smartwatch', 'Fitness smartwatch', 120.0, 20);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Camera', 'Digital SLR camera', 700.0, 7);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Microphone', 'Condenser microphone', 90.0, 15);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Graphics Card', 'High-performance GPU', 500.0, 6);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Motherboard', 'ATX motherboard', 150.0, 10);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('RAM', '16GB DDR4 RAM', 80.0, 25);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('CPU', '8-core processor', 320.0, 8);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Power Supply', '650W PSU', 70.0, 15);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('SSD', '500GB NVMe SSD', 100.0, 20);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Laptop Bag', 'Waterproof laptop bag', 45.0, 30);
