INSERT INTO PRODUCT (ID, NAME, DESCRIPTION, PRICE, QUANTITY, VERSION) VALUES (1, 'Laptop', 'High-end laptop', 1500.0, 5, 0);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION, PRICE, QUANTITY, VERSION) VALUES (2, 'Mouse', 'Wireless mouse', 25.0, 50, 0);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION, PRICE, QUANTITY, VERSION) VALUES (3, 'Keyboard', 'Mechanical keyboard', 75.0, 20, 0);
