-- Sequences
CREATE SEQUENCE CATEGORY_SEQ START WITH 0 INCREMENT BY 1;
CREATE SEQUENCE PRODUCT_SEQ START WITH 0 INCREMENT BY 1;
CREATE SEQUENCE USER_SEQ START WITH 0 INCREMENT BY 1;

-- Category table
CREATE TABLE CATEGORY (
    ID BIGINT DEFAULT NEXT VALUE FOR CATEGORY_SEQ PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

-- Product table
CREATE TABLE PRODUCT (
    ID BIGINT DEFAULT NEXT VALUE FOR PRODUCT_SEQ PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRICE DOUBLE,
    QUANTITY INT,
    VERSION BIGINT DEFAULT 0,
    CATEGORY_ID BIGINT,
    CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);