-- Insert categories
INSERT INTO CATEGORY (NAME) VALUES ('Computers');
INSERT INTO CATEGORY (NAME) VALUES ('Peripherals');
INSERT INTO CATEGORY (NAME) VALUES ('Accessories');
INSERT INTO CATEGORY (NAME) VALUES ('Audio/Video');

-- Insert products with category_id
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('Laptop', 'High-end laptop', 1500.0, 5, 0);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('Mouse', 'Wireless mouse', 25.0, 50, 1);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('Keyboard', 'Mechanical keyboard', 75.0, 20, 1);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('Monitor', '24-inch LED monitor', 200.0, 15, 1);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('Printer', 'Laser printer', 120.0, 10, 1);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('Webcam', 'HD webcam', 60.0, 30, 2);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('Headphones', 'Noise-cancelling headphones', 150.0, 25, 2);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('Speakers', 'Bluetooth speakers', 80.0, 40, 2);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('External HDD', '1TB external hard drive', 90.0, 20, 3);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('USB Drive', '64GB USB 3.0', 15.0, 100, 3);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('Tablet', '10-inch Android tablet', 250.0, 12, 0);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('Smartphone', 'Latest model smartphone', 900.0, 8, 0);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('Charger', 'Fast USB-C charger', 30.0, 60, 3);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('Router', 'Wi-Fi 6 router', 180.0, 10, 1);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('Projector', 'HD projector', 400.0, 5, 2);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('Smartwatch', 'Fitness smartwatch', 120.0, 20, 0);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('Camera', 'Digital SLR camera', 700.0, 7, 2);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('Microphone', 'Condenser microphone', 90.0, 15, 2);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('Graphics Card', 'High-performance GPU', 500.0, 6, 0);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('Motherboard', 'ATX motherboard', 150.0, 10, 0);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('RAM', '16GB DDR4 RAM', 80.0, 25, 0);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('CPU', '8-core processor', 320.0, 8, 0);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('Power Supply', '650W PSU', 70.0, 15, 0);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('SSD', '500GB NVMe SSD', 100.0, 20, 0);
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY, CATEGORY_ID) VALUES ('Laptop Bag', 'Waterproof laptop bag', 45.0, 30, 3);

-- Insert users and their passwords
INSERT INTO APP_USER (USERNAME, PASSWORDHASH, ROLE) VALUES ('admin', '$argon2i$v=19$m=65536,t=2,p=1$TLathQVyC2N25dHbB3jeEA$sTfcKGCsvLu6UvrwPh+/L33fOBNb06CKKSFap5Gykxs', 'admin'); -- pass hashed with argon2 for admin is admin123
INSERT INTO APP_USER (USERNAME, PASSWORDHASH, ROLE) VALUES ('user', '$argon2i$v=19$m=65536,t=2,p=1$TT9umGqLiDlmGpuxPknfTQ$Y5wkhD/uHsZCJo6EZhRVZQYI5AYcsLpWnG5gxgk8HlQ', 'user'); -- pass hashed with argon2 for user is user123
